export const data = {
    products: [
        {
            title: 'Aceite de oliva',
            description: 'Aceite de oliva Coinco.',
            stock: 5,
            price: 900,
            offertPrice: 780,
            category: 'Aceites',
            image: 'https://http2.mlstatic.com/D_NQ_NP_717139-MLA44123216896_112020-O.webp',
            id: 0,
        },
        {
            title: 'Pasta de maní',
            description: 'Pasta de maní natural Entre nuts',
            stock: 5,
            price: 1000,
            offertPrice: 800,
            category: 'Pasta de maní',
            image: 'https://laduvalina.com.ar/wp-content/uploads/2021/12/Natu.jpg',
            id: 1,
        },
        {
            title: 'Leche de almendras',
            description: 'Leche de almendras Amande.',
            stock: 1,
            price: 500,
            category: 'Leches',
            image: 'http://d3ugyf2ht6aenh.cloudfront.net/stores/001/130/674/products/leche-almdras-sabor-original-11-bef3be7ce614317b9516206595720877-640-0.png',
            id: 2,
        },
        {
            title: 'Barra proteica',
            description: 'Barra proteica OLYMPIC.',
            stock: 1,
            price: 260,
            offertPrice: 200,
            category: 'Barras',
            image: 'https://well-home.fitness/wp-content/uploads/2021/04/WhatsApp-Image-2021-04-07-at-11.59.40-2.jpeg',
            id: 3,
        },
        {
            title: 'Galletas Vital',
            description: 'Galletas integrales con stevia Vital.',
            stock: 1,
            price: 450,
            category: 'Galletas',
            image: 'image.png',
            id: 4,
        },
        {
            title: 'Galletas Cachafaz',
            description: 'Galletas integrales Cachafaz.',
            stock: 1,
            price: 500,
            offertPrice: 450,
            category: 'Galletas',
            image: 'https://carrefourar.vtexassets.com/arquivos/ids/175902/7798128000684_02.jpg?v=637468571819430000',
            id: 5,
        }
    ]
}